### ISSUE TITLE
子集化时应避开数字，以免potplayer使用内置ass渲染功能时出现问题

### ISSUE THREAD

**Issue by honeyjuice** [DYY-Studio/AddSubFontMKV_py#11]
图一为，手动加入完整数字0~9的渲染效果
![图片](https://user-images.githubusercontent.com/32090001/189324044-321e5989-9fc7-40a2-aba5-39fca7b8e8ce.png)

图二为，缺少完整数字0~9的渲染效果
![图片](https://user-images.githubusercontent.com/32090001/189324228-1dd0edf2-550d-482b-893f-9107f58d513b.png)

已确认字体中含有16 1803 3989这些数字字体，但是缺少未调用到的5、7，缺少了这些数字导致potplayer内置ass功能渲染异常
![图片](https://user-images.githubusercontent.com/32090001/189327767-77211f94-a9dd-4bd9-8bf2-b38dcc355bc1.png)

用于测试的字幕：
[[SweetSub] The Orbital Children - 06.chs.zip](https://github.com/DYY-Studio/AddSubFontMKV_py/files/9534429/SweetSub.The.Orbital.Children.-.06.chs.zip)

字体文件：
https://mega.nz/file/nscRkIiQ#ndjtIUSvbTVp58v9zWJg98uYmmXh0RvweYqIpZ0idCI

演示画面中的字幕时间段：
Dialogue: 0,0:20:50.10,0:20:53.48,Sign,,0,0,0,,{\an1\fs65\c&H000000&\3c&HFFFFFF&\pos(172,636)\fnSource Han Sans SC}宇宙偶像事业大获成功，\N正在月球上举办巡回演唱会\N现在的关注人数有 16 亿 1803 万 3989 人

**Comment by DYY-Studio** [comment]
已参考各组织的子集化方式，之后会保留全部数字

**Comment by VEWION** [comment]
问题来源：https://bbs.acgrip.com/forum.php?mod=redirect&goto=findpost&ptid=9792&pid=92793
问题复述：
缺少字母b时会导致引号渲染错误

建议应该同样参考其他工具的子集化方式英文字母和数字均全部保留

**Comment by DYY-Studio** [comment]
> 问题来源：https://bbs.acgrip.com/forum.php?mod=redirect&goto=findpost&ptid=9792&pid=92793 问题复述： 缺少字母b时会导致引号渲染错误
> 
> 建议应该同样参考其他工具的子集化方式英文字母和数字均全部保留

之前拆过LoliHouse的子集化字体来看，是没有保留全部英文字母的，故目前也是这样干的
可能以后会保留字母b？等我下周末有空看看什么情况
