### ISSUE TITLE
特殊符号导致微软雅黑子集化失败

### ISSUE THREAD

**Issue by VEWION** [DYY-Studio/AddSubFontMKV_py#16]
特殊符号为：♩♪♫
尝试子集化时失败，自动中断，把子集化失败中断改为False后再次执行报错：
```
[WARNING] 字体"MicrosoftYaHei.ttf"子集化失败，将会保留完整字体



Traceback (most recent call last):
  File "D:\Downloads\ASFMKV_py1.02-pre9.py", line 2614, in <module>
    loadMain()
  File "D:\Downloads\ASFMKV_py1.02-pre9.py", line 2536, in loadMain
    cFontSubset(font_info)
  File "D:\Downloads\ASFMKV_py1.02-pre9.py", line 2219, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k],
  File "D:\Downloads\ASFMKV_py1.02-pre9.py", line 1821, in main
    else: newasspath.append(assFontChange(multiAss[s][0], newfont_name, s, multiAss[s][1], multiAss[s][3], multiAss[s][2], outdir[0], fn_lines=fn_lines))
  File "D:\Downloads\ASFMKV_py1.02-pre9.py", line 1235, in assFontChange
    fn_line = fn_line.replace(k, k.replace(fname, newfont_name[fname][1]))
TypeError: replace() argument 2 must be str, not None
```

**Comment by DYY-Studio** [comment]
微软雅黑里面是不是没有这些特殊符号？子集化失败应该是这个问题

至于关闭子集化失败中断后崩溃这个是程序的问题
没做对None的处理应该是，这功能我几百年没用过了

去做个核酸先，早上我检查一下

**Comment by DYY-Studio** [comment]
检查发现微软雅黑的“杂项符号”区域（u2600-u26FF）并不包含以上测试符号（u2669-u266B）
![image](https://user-images.githubusercontent.com/48157880/190286599-8584668d-0fe6-4af9-a8c1-6b7f5cc42fa4.png)

至于关闭子集化失败中断后就崩的问题，我一会测试之后修一下

**Comment by VEWION** [comment]
> 检查发现微软雅黑的“杂项符号”区域（u2600-u26FF）并不包含以上测试符号 ![image](https://user-images.githubusercontent.com/48157880/190286599-8584668d-0fe6-4af9-a8c1-6b7f5cc42fa4.png)
> 
> BUG我一会修

咦，神奇居然没有，奇怪字幕组还特地指定这些符号用这字体，不知道是不是想手动fallback（

好的，静待修复，谢谢

**Comment by VEWION** [comment]
Preview11已解决，Preview12E显示字符不在字体内，子集化失败中断为False时依然会自动中断，你看看用不用把这issue close了还是先修好再close？

**Comment by DYY-Studio** [comment]
早上测的时候从9_2f1开始就没发现有断掉的问题）我在12E额外加了点东西防止出这种怪事
12E那个字符检测是新加的功能，还没接到旧的内容里。这么看挺成功，不枉费我爆肝。
之后可能加个选项可以直接跳过对这种超范围字符的子集化？

close不着急吧，放着先，等12多测一点再说
