### ISSUE TITLE
发现未使用的字体

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#2]
今天在封装银魂317-327时，发现了字幕未使用的字体，却在命令行中提示了如下字段，但是视频最后却又未封装

[WARNING] 字体"MECHAG.TTF"子集化失败，将会保留完整字体

**Comment by DYY-Studio** [comment]
由于疫情原因，设备不在身边，清明前是没办法修复了。
希望能够提供对应的字幕文件以便debug和下一步的修复。

视频未封装是Preview3新增的强制停止（可以在自定义变量 errorStop 调整）。如果子集化错误就会停止程序，以防出现更大的问题，或者出现不被用户所期望的封装整个字体的情况。

看起来我好像忘记修改warning信息了。
