### ISSUE TITLE
检查字幕所需字体

### ISSUE THREAD

**Issue by theRainight** [DYY-Studio/AddSubFontMKV_py#21]
当检查并列出字幕所需字体时，可否将No Found 的所有字体直接在最后列出来？复制一个字体划一下鼠标挺费劲的感觉
[![pSdU6pQ.png](https://s1.ax1x.com/2023/01/29/pSdU6pQ.png)](https://imgse.com/i/pSdU6pQ)

**Comment by DYY-Studio** [comment]
了解了，之后出个无格式输出吧

**Comment by DYY-Studio** [comment]
![图片](https://user-images.githubusercontent.com/48157880/216805723-566e6125-beb5-4e5a-97f2-f05566f6509c.png)

**Comment by theRainight** [comment]
:kissing_heart:
