### ISSUE TITLE
程序不显示错误崩溃

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#22]
诸神的字幕，检查字体或子集化均崩溃，程序用的是15fix1
[诸神字幕](https://baleines.lanzoul.com/iVhh90mlxjsj)
另外发现有时子集化的字体，会出现某个字加粗的现象，而加载字体外挂字幕却正常显示，不知是不是bug

**Comment by DYY-Studio** [comment]
![图片](https://user-images.githubusercontent.com/48157880/216803987-741e7a19-d458-4c86-9aa9-c90f9976b00f.png)
诸神留了一行完全没用的空行来隔开各部分内容，这行不是Comment注释标头，Style还设置的是ASS中并没有规定的Default
一般来说这种用来分割不同部分字幕的行应该是注释行……
之前没碰到过这么操作的，导致程序没做这个方面的对应）

关于子集化的字体出现加粗现象，希望提供一下对应字幕，我好看看是不是又是ASS分析部分有问题什么的

**Comment by Duan-rax** [comment]
[字体加粗字幕](https://baleines.lanzoul.com/i0InS0moquib)
里面有几张截图，是第四集2min50s附近，未加粗的是外挂字幕的显示效果

**Comment by DYY-Studio** [comment]
我一拿到一看到微软雅黑就在想肯定又是这玩意搞事了
没子集化之前看了一下第四话的字幕内容，发现样式 **ThisTitle** 是 **微软雅黑Bold**，而其它都是 **微软雅黑**
而截图中有加粗的都是 **ThisTitle** 中的字符 “**这是画吗？**”

没把**微软雅黑**放进去
![图片](https://user-images.githubusercontent.com/48157880/216810348-d25e1248-a3ed-4a36-8b48-cd076c03ea83.png)
并且使用**微软雅黑**的样式也错误的被替换成了**微软雅黑Bold**

![图片](https://user-images.githubusercontent.com/48157880/216810474-5fd8bc32-2c54-4988-b405-553ad2fb1291.png)

**Comment by DYY-Studio** [comment]
已查出问题
在处理创建的字体子集时，由于程序内部比较的是字体在字幕样式中的名称，所以导致了**微软雅黑Bold**将**微软雅黑**覆盖
修复中

**Comment by DYY-Studio** [comment]
已修正 **Pre15 Fix 3**
![图片](https://user-images.githubusercontent.com/48157880/216814956-34a2516b-b9c2-446f-9deb-afe0025633d5.png)

**Comment by Duan-rax** [comment]
> Pre15 Fix 3
我这边使用ListAssFont检查字幕所用字体时直接崩溃退出了，但是可以正常封装，<s>字幕还是微软雅黑的那些</s>，又随便下了几个，发现全部无法显示

**Comment by DYY-Studio** [comment]
改了函数忘记改接收了
![图片](https://user-images.githubusercontent.com/48157880/216821150-8ea80670-04ab-4e23-a49d-a929904c8d52.png)

还有崩溃后直接退出是以前为了用断点调试而把那部分注释起来了，看起来好几个版本都忘记删掉注释了）
Fix3已经更新到第二个版本

**Comment by DYY-Studio** [comment]
今早想了一下好像还是会有问题
忘记改fn标签的字体处理了
这几天没什么空，看看能不能应急一下

**Comment by DYY-Studio** [comment]
**Pre 15 Fix 3-3** 应该把fn标签替换修好了，不知道会不会出什么别的问题

**Comment by Duan-rax** [comment]
**问一个困惑很久的问题，就是同时封装多个字幕时，有时会失败，然后报这个错，请问是不是字体之类的原因。**

Traceback (most recent call last):
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f3.py", line 3453, in <module>
    loadMain()
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f3.py", line 3368, in loadMain
    cFontSubset(font_info)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f3.py", line 2751, in cFontSubset
    newasspaths, newfont_name, mkvr = main(font_info2, media_ass[k],
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f3.py", line 2237, in main
    newfont_name = assFontSubset(assfont, fo, font_info)
  File "C:\Users\Duanp\Desktop\AddSub\ASFMKV_pre15f3.py", line 1408, in assFontSubset
    s = k.split('?') + [assfont[k][0], assfont[k][1], assfont[k][2], str(assfont[k][4]), str(assfont[k][5])]
IndexError: list index out of range

**Comment by DYY-Studio** [comment]
assfont的update函数忘记更新了，笑死，漏这漏那的）
两分钟马上搞定

**Comment by Duan-rax** [comment]
> assfont的update函数忘记更新了，笑死，漏这漏那的） 两分钟马上搞定
[提供一些多字幕封装的报错字幕](https://baleines.lanzoul.com/iqcWZ0nj3dih)

**Comment by DYY-Studio** [comment]
发现问题了。和上面解决的那个是不一样的。
fn_lines设计指向的是同样文件长度的ASS（即仅同一字幕组的简繁），而现在出现了两个行数差别极大的字幕组
然后就索引到外面去了（在 **364行** 的ASS中找 **第672行** 的`\fn`标签）

这个算是元老级的BUG了。
说实话本来应该把fn_lines对应到字幕文件的，看来是当年偷懒了。现在暂时修修补补一下。
顺带还发现了`\fn`标签不能替换的问题，以及字体还原信息写入不合规范的问题
