### ISSUE TITLE
Pre17预告: 完整的sublangs功能

### ISSUE THREAD

**Issue by DYY-Studio** [DYY-Studio/AddSubFontMKV_py#26]
自从1.00以来，该功能一直处于是个屁的状态，设置需要打开python文件，调整里面的选项，而不能每次根据输入的字幕询问用户

**非常的麻烦啊！！！**

在结束某些大事之后，6月初，大概，Preview 17 将会带着这个一拖再拖的ASFMKV传统机能回归

至于 PyQt Beta3，我觉得GUI真的好烦啊，应该6月中旬没事干会搞出来的

**Comment by Duan-rax** [comment]
大佬有没有像FontLoaderSub那样，考虑加入字体缓存文件的支持，从而减少启动时加载字体的时间

**Comment by DYY-Studio** [comment]
没用过FontLoaderSub……不太清楚它的工作情况
字体读取的功能最早就是参照ListAssFont的，那位也是扫一遍字体。而且每次丢进去都要扫）

你这么一说我倒是有想法了，你的点子很有意思，我觉得可以像老ASFMKV的ExtLIST缓存那样实现。

而且dump出去应该就行了。实现不是很难。

**Comment by Duan-rax** [comment]
https://github.com/MkvAutoSubset/MkvAutoSubset
https://bbs.acgrip.com/forum.php?mod=viewthread&tid=9070&highlight=mkvtoo
这是看到的另一个项目，这个项目是有字体缓存的。

**Comment by DYY-Studio** [comment]
谢谢，姑且还是不打算参考其他项目的具体做法。知道有这样功能就行了。
我算是比较极端的一类，前段时间翻个视频也是为了文风不受影响和其他字幕组翻的整个系列都避开了，之后看这个系列就算不做字幕也一直在啃生肉。
现在我大概有点子了，实现起来不难。应该能轻松搞定，吧。

这样一聊我才想起来慢速盘这样子读字体是挺痛苦的。我测试用的是西数SN750，前段时间用了下旧的金士顿UV300，肉眼可见慢。

更别说机械硬盘的兄弟们了。

所以这个版本就加吧。

看看这周末得不得空，不得可能得6月之后了
