### ISSUE TITLE
Pre17运行时的小问题

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#27]
[字幕文件：](https://baleines.lanzoul.com/i7npE0xjeibg)

问题日志：
字体输出路径: "E:\Downloads\[LPSub&LP-Raws] 4-nin wa Sorezore Uso o Tsuku [Ma10p_1080p]\Fonts\[LPSub] 4-nin wa Sorezore Uso o Tsuku 07 (BDRip 1080p HEVC-YUV420P10 FLAC).sc"
[19/19] 正在子集化……
字幕输出路径: "E:\Downloads\[LPSub&LP-Raws] 4-nin wa Sorezore Uso o Tsuku [Ma10p_1080p]\subs"
找不到字体 思源宋體 HK Heavy 位于行38
特效标签 {\fn@思源宋體 HK Heavy\c&H000000&\bord0\fs45\frz300.2\pos(745,728)}
可能是该标签指定字体未被使用，或出现了BUG，请注意检查输出

等待  0 秒，按一个键继续 ...

相关字体：[  42] Source Han Serif HK Heavy|思源宋體 HK Heavy <SourceHanSerifHK-Heavy.ttf>

推测字幕里同一个字体用了两个不同的名字。多见于同一作品封装多字幕组。

**Comment by DYY-Studio** [comment]
可能是我忘记切开多名称或者只用了一个名称，这周末或者下周末我看看（也有可能发癫这几天就搞定）。
我只能说这个提示我当时搞出来真是太对了，真能试出来

下次能否把字体也附了，离谱sub这个是真离谱啊。

**Comment by DYY-Studio** [comment]
确实是没切分，大概搞定了，还没测试完。

**Comment by Duan-rax** [comment]
我的问题，下次一定附上。

**Comment by DYY-Studio** [comment]
常用的就算了，就是离谱Sub用了地区特定思源宋体子集(HK)比较离谱，更纱黑体我之前也没有搞下来。

一般来说应该用HC吧草）
