### ISSUE TITLE
部分诸神字幕组制作的字幕封装后出现字体缩小且重叠的情况

### ISSUE THREAD

**Issue by Duan-rax** [DYY-Studio/AddSubFontMKV_py#3]
以前出现过在人渣的本源这部作品里，今天在Love Live的剧场版中同样出现了
[外挂-图片](https://pic.arest.cc/images/2022/04/20/MPV-00_12_06.100-N0002.jpg)
[封装-图片](https://pic.arest.cc/images/2022/04/20/MPV-00_11_57.634-N0001.jpg)
[字幕文件](https://baleines.lanzoul.com/iY7a203j9ocd)
更新，使用了[另一个项目](https://github.com/KurenaiRyu/MkvAutoSubset)，子集化字体后手动封装，字幕显示正常，已把字幕文件更新

**Comment by DYY-Studio** [comment]
收到，正在排查
最近地平线4玩疯了，咕了好久了）

**Comment by DYY-Studio** [comment]
已查出，应该是诸神在样式名里写了字体名，而ASFMKV Py的替换过于暴力，一起换了
DirectVobSub手动载入时报错了
![image.png](https://s2.loli.net/2022/04/23/CIMgi56NJsv7rGy.png)

还有就是我的注释又写到[Script Info]上面去了——

**Comment by DYY-Studio** [comment]
用手头有的华盟和澄空的内嵌版本挂上试了试，应该是修复了……
