### ISSUE TITLE
字幕格式错误导致程序错误退出（缺少样式、逗号分隔不正确…）

### ISSUE THREAD

**Issue by tb114514** [DYY-Studio/AddSubFontMKV_py#37]
版本19f1可以正常分析，20会报错:
正在尝试从字幕所在文件夹载入字体...
正在读取字体信息...
3/3 100.00% 【缓存】D:\Desktop\银魂
"29.ass" - UTF-8-SIG
"30.ass" - UTF-8-SIG
"31.ass" - UTF-8-SIG
"32.ass" - UTF-8-SIG
"33.ass" - UTF-8-SIG
"34.ass" - UTF-8-SIG
"35.ass" - UTF-8-SIG
"36.ass" - UTF-8-SIG
"37.ass" - UTF-8-SIG
"38.ass" - UTF-8-SIG
"39.ass" - UTF-8-SIG
"40.ass" - UTF-8-SIG
"41.ass" - UTF-8-SIG
"42.ass" - UTF-8-SIG
"43.ass" - UTF-8-SIG
"44.ass" - UTF-8-SIG
"45.ass" - UTF-8-SIG
"46.ass" - UTF-8-SIG
"47.ass" - UTF-8-SIG
"48.ass" - UTF-8-SIG
"49.ass" - UTF-8-SIG
"50.ass" - UTF-8-SIG
"51.ass" - UTF-8-SIG
"52.ass" - UTF-8-SIG

Traceback (most recent call last):
  File "D:\game\MKVToolNix\ASFMKV_pre20.py", line 4094, in <module>
    loadMain()
  File "D:\game\MKVToolNix\ASFMKV_pre20.py", line 3979, in loadMain
    cListAssFont(font_info)
  File "D:\game\MKVToolNix\ASFMKV_pre20.py", line 2929, in cListAssFont
    fontlist = assFontList(assInfo, eventTagsSplit(assInfo, False))
  File "D:\game\MKVToolNix\ASFMKV_pre20.py", line 337, in eventTagsSplit
    eventftext = events[i]['Text']
KeyError: 'Text'

**Comment by DYY-Studio** [comment]
字幕52提供一下，直接用压缩包应该就可以上传吧。
20换了新的分析函数，19f1虽然屎山一点但也可以正常跑，有问题先用19f1。

怀疑是ASS文件格式本身的问题，是不是不太规范？

**Comment by tb114514** [comment]
> 字幕52提供一下，直接用压缩包就可以上传吧。 20更换了新的分析函数，19f1虽然破了山一点但也可以正常运行，担心先用19f1。
> 
> 怀疑是ASS文件格式本身的问题，是不是不太规范？


[正片.zip](https://github.com/user-attachments/files/15515719/default.zip)

**Comment by DYY-Studio** [comment]
收到，经过检查发现是字幕本身的问题。
**19f1**版本估计也处理错误了，但是没有直接崩溃。我很怀疑结果是否准确。
问题发生在字幕`52.ass`行`371`时间`0:24:23.93,0:24:29.77`，此处**缺少一个逗号分隔**。
故**20**版本抛出了异常。

如果您使用Aegisub，它也会抛出错误告诉您该行有误
![image](https://github.com/DYY-Studio/AddSubFontMKV_py/assets/48157880/e049f5e9-3cf4-4bc9-9390-7468b7af3238)

该行的正确写法为
`Dialogue: 0,0:24:23.93,0:24:29.77,*Default,NTP,0000,0000,0000,,压力是导致秃顶的原因 所以请注意不要压力太大\N但这样一来反而容易堆积压力\N所以归根到底我们无能为力`

**Comment by DYY-Studio** [comment]
考虑在接下来的版本中预先确认是否每一行都有正确的逗号分隔，并在错误时抛出提示

函数设计时考虑的是用户的字幕是「**完全正常**」的，没有想到这么多幺蛾子

**Comment by refined-fish** [comment]
> 考虑在接下来的版本中预先确认是否每一行都有正确的逗号分隔，并在错误时抛出提示
> 
> 函数设计时考虑的是用户的字幕是「**完全正常**」的，没有想到这么多幺蛾子

遇到了类似的BUG，尝试更换19f1能正常运行，如下为报错的字幕文件

[[DBD-Raws][我的英雄学院 第四季][02][1080P][BDRip][HEVC-10bit][FLAC].简体中文.zip](https://github.com/user-attachments/files/16645318/DBD-Raws.02.1080P.BDRip.HEVC-10bit.FLAC.zip)

**Comment by DYY-Studio** [comment]
我觉得这个版本我标得很清楚了）

`未定义 行202 所用样式"in"`

这是字幕本身的问题，不是程序的问题
没设置样式来怪我缺字就不好了

这里的「行202」指的是用Aegisub打开后看到的第203行，不是文本编辑器打开后的第202行

![图片](https://github.com/user-attachments/assets/8d8ac003-ba42-4f1c-bd7b-2fd90b6a4bb2)

忘记+1显示了，马上修

**Comment by refined-fish** [comment]
> 我觉得这个版本我标得很清楚了）
> 
> `未定义 行202 所用样式"in"`
> 
> 这是字幕本身的问题，不是程序的问题 没设置样式来怪我缺字就不好了
> 
> 这里的「行202」指的是用Aegisub打开后看到的第203行，不是文本编辑器打开后的第202行
> 
> ![图片](https://private-user-images.githubusercontent.com/48157880/358890505-8d8ac003-ba42-4f1c-bd7b-2fd90b6a4bb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjcxODYsIm5iZiI6MTcyMzk2Njg4NiwicGF0aCI6Ii80ODE1Nzg4MC8zNTg4OTA1MDUtOGQ4YWMwMDMtYmE0Mi00ZjFjLWJkN2ItMmZkOTBiNmE0YmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YzMxNzNlM2M0MDhhZGQxOWVmNzZmNzM3ZWE4NTNlMjYwNDAzM2FkZjI0YjQzZmYyYzIzM2M2NzVmYWQ0MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZhmI4ytcsTS7lFbvt7u1ntE5hv4V53EQheigykchKI)
> 
> 忘记+1显示了，马上修

我完全懂了😂，不好意思
