### ISSUE TITLE
直向字幕無法正確子集化

### ISSUE THREAD

**Issue by RomaYun323** [DYY-Studio/AddSubFontMKV_py#39]
原字幕文件字體有表示@
Style: EDJP,@DFPGiHi-W7,36,&H00FFFFFF,&HF0FFFFFF,&H00000000,&HF0FFFFFF,0,0,0,0,100,100,0,-90,1,1,0,2,15,15,15,1
Style: EDCN-CHS,@华康魏碑W7(P),36,&H00FFFFFF,&H00FFFFFF,&H00000000,&H32FFFFFF,0,0,0,0,100,100,1,-90,1,1,0,8,10,10,16,1
Style: EDCN-CHT,@華康魏碑體(P),36,&H00FFFFFF,&H00FFFFFF,&H00000000,&H32FFFFFF,0,0,0,0,100,100,1,-90,1,1,0,8,10,10,16,1

![image](https://github.com/user-attachments/assets/48ea2b53-f608-4766-afc9-98d8ce87cc94)

**Comment by DYY-Studio** [comment]
应该是子集化后前缀「@」没有还原导致的，近几天会进行修复
