### ISSUE TITLE
能否增加默认字幕轨道设置，目前似乎是按照文件名来排序的

### ISSUE THREAD

**Issue by refined-fish** [DYY-Studio/AddSubFontMKV_py#41]
## 问题描述
测试发现目前封装字幕的顺序似乎是按照文件名排序来的，而且文件名排在首位的字幕为默认轨道。

## 期望
是否能让用户自定义选择默认的字幕轨道，例如匹配字幕文件名的某些字段（中文，简体......），或者匹配文件名中的语言代码（zh，chi......），目前“繁体中文”因为按文件名排序排在“简体中文”之前，因此封装出来默认轨道也是“繁体中文”，希望有方法能将“简体中文”设置为默认轨道。

## 环境
顺带一提目前使用的为pre13版本，虽然在说明中看见提到了pre17等更新版本，但是我似乎未能找到

**Comment by DYY-Studio** [comment]
新的在Release，或者dev分支里的_dev也是最新版本的。
main分支那一坨我还没想好怎么整。
默认轨道可以考虑，下个版本加吧。

**Comment by refined-fish** [comment]
> 新的在Release，或者dev分支里的_dev也是最新版本的。 main分支那一坨我还没想好怎么整。 默认轨道可以考虑，下个版本加吧。

感谢回复！我发现是我晃眼把Packages看成Release了，Packages为none当成了没有Release，现在已经找到了。

顺便问问未来脚本能否识别“字幕文件名”中除“视频名”以外的部分，例如“VideoName.chi.ass”识别chi来自动匹配字幕轨道的语言信息。这样只要字幕文件按照约定都在尾部写上ISO语言代码（或其他特定字符），就无需手动指定语言信息了。这样能处理目前手动指定方案无法处理的多语言字幕且顺序不一定完全一致情况。

例如字幕名为：“VideoName.chi.ass”。——前面的VideoName用来匹配同名视频文件，尾部的chi则自动匹配语言编码“中文”，将此字幕轨道的语言信息匹配为“中文”，同时将轨道名称也设置为“中文”

还有一个问题是番剧常见字幕文件有“简中”和“繁中”，但查询发现ISO-639-3编码中似乎是按照语音来分类，汉语虽然被分为很多地方语言，但是繁体中文并不独立，与简体中文的代码都是chi/zh，轨道语言信息也都“[中文]”无法区别开来，是否考虑支持独立“繁体中文”的RFC4646或RFC 1766编码标准？

**Comment by refined-fish** [comment]
> > 新的在Release，或者dev分支里的_dev也是最新版本的。 main分支那一坨我还没想好怎么整。 默认轨道可以考虑，下个版本加吧。
> 
> 感谢回复！我发现是我晃眼把Packages看成Release了，Packages为none当成了没有Release，现在已经找到了。
> 
> 顺便问问未来脚本能否识别“字幕文件名”中除“视频名”以外的部分，例如“VideoName.chi.ass”识别chi来自动匹配字幕轨道的语言信息。这样只要字幕文件按照约定都在尾部写上ISO语言代码（或其他特定字符），就无需手动指定语言信息了。这样能处理目前手动指定方案无法处理的多语言字幕且顺序不一定完全一致情况。
> 
> 例如字幕名为：“VideoName.chi.ass”。——前面的VideoName用来匹配同名视频文件，尾部的chi则自动匹配语言编码“中文”，将此字幕轨道的语言信息匹配为“中文”，同时将轨道名称也设置为“中文”
> 
> 还有一个问题是番剧常见字幕文件有“简中”和“繁中”，但查询发现ISO-639-3编码中似乎是按照语音来分类，汉语虽然被分为很多地方语言，但是繁体中文并不独立，与简体中文的代码都是chi/zh，轨道语言信息也都“[中文]”无法区别开来，是否考虑支持独立“繁体中文”的RFC4646或RFC 1766编码标准？

看了一下，ISO-639-3是通过单独的“文字”字段来区别繁体的，例如MKVTools中如下图，但是实操了一下，封装完在播放器中还是显示为“中文”，似乎没有太大的意义🤣
![image](https://github.com/user-attachments/assets/54791e3a-bfc1-4895-afd5-765f20699586)

**Comment by DYY-Studio** [comment]
![图片](https://github.com/user-attachments/assets/61f949d8-1d19-4f25-924c-d5a951d5c693)

Matroska从V4支持了BCP 47（RFC 5646），但是`LanguageBCP47`标签和原有的使用ISO-639-2的`Language`标签是两个段，播放器和Mediainfo只会读取`Language`，而不会去尝试读取`LanguageBCP47`
所以目前…似乎并没有什么用，要等分离器支持。

别的…Matroska不支持啊）而且RFC 4646和RFC 1766已经被RFC 5646取代了x

目前我这边的实现手段是直接`mkvmerge --list-languages`获取ISO-639以阻止用户的错误输入，所以暂时没兼容BCP 47。
要兼容也不是不行，但是目前来看好像作用不是很大…

![图片](https://github.com/user-attachments/assets/4d64788a-ff4b-47c6-9813-f673e277d24e)

**文件名除“视频名”以外的部分**目前会作为轨道`Title`输入给mkvmerge。
这个部分有时候写法并不是太规范，比如我还会拿来标记不同字幕组`Sumisora-SC`，`chs` `cht` `sc` `tc`这种也不是规范写法，而且字幕渲染滤镜一般也将这一部分处理为该字幕的标题，所以之前都是这个考虑。
从这里识别语言理论上可以，就是要整个很麻烦的表了。

或者考虑让用户自己映射？诶，这倒是个好想法。

那对于有这部分内容的字幕可以不再使用文件名排序，而是按照这部分映射。
彳亍，会试着实现的。

**Comment by refined-fish** [comment]
> ![图片](https://private-user-images.githubusercontent.com/48157880/358886993-61f949d8-1d19-4f25-924c-d5a951d5c693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjY1MTEsIm5iZiI6MTcyMzk2NjIxMSwicGF0aCI6Ii80ODE1Nzg4MC8zNTg4ODY5OTMtNjFmOTQ5ZDgtMWQxOS00ZjI1LTkyNGMtZDVhOTUxZDVjNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3MzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNDExZTk1NzM3MTNmYmJiZjQ1ZGQ0YTkwNWRmNjBiZGYxNDZhYTM3NGUxZTBkOTFjZDgyN2Y5NTg3MTAxODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fS-tL4mLrawnM2Uj75A2ym1Vw_EPV7acByvVNu_l_r0)
> 
> Matroska从V4支持了BCP 47（RFC 5646），但是`LanguageBCP47`标签和原有的使用ISO-639-2的`Language`标签是两个段，播放器和Mediainfo只会读取`Language`，而不会去尝试读取`LanguageBCP47` 所以目前…似乎并没有什么用，要等分离器支持。
> 
> 别的…Matroska不支持啊）而且RFC 4646和RFC 1766已经被RFC 5646取代了x
> 
> 目前我这边的实现手段是直接`mkvmerge --list-languages`获取ISO-639以阻止用户的错误输入，所以暂时没兼容BCP 47。 要兼容也不是不行，但是目前来看好像作用不是很大…
> 
> ![图片](https://private-user-images.githubusercontent.com/48157880/358887524-4d64788a-ff4b-47c6-9813-f673e277d24e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjY1MTEsIm5iZiI6MTcyMzk2NjIxMSwicGF0aCI6Ii80ODE1Nzg4MC8zNTg4ODc1MjQtNGQ2NDc4OGEtZmY0Yi00N2M2LTk4MTMtZjY3M2UyNzdkMjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3MzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMjhkMmJjNTYzNzFkYWVjOWMyZmM3MzY4YmY2MGQ0Y2YzZmM2Y2RlYjBkNGIyMWY2MWY2MTgzNTAxMTJkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.24Knqxgu8Zd9RIJRyqvDHHeDcgVzU2q_ZnqqBPzqBfk)
> 
> **文件名除“视频名”以外的部分**目前会作为轨道`Title`输入给mkvmerge。 这个部分有时候写法并不是太规范，比如我还会拿来标记不同字幕组`Sumisora-SC`，`chs` `cht` `sc` `tc`这种也不是规范写法，而且字幕渲染滤镜一般也将这一部分处理为该字幕的标题，所以之前都是这个考虑。 从这里识别语言理论上可以，就是要整个很麻烦的表了。
> 
> 或者考虑让用户自己映射？诶，这倒是个好想法。
> 
> 那对于有这部分内容的字幕可以不再使用文件名排序，而是按照这部分映射。 彳亍，会试着实现的。

确实，我也是才发现播放器并不识别扩充的语言代码，加上对播放体验没有任何提升🤣，本来我是想能直接在字幕选择菜单区别“简中”“繁中”的，这么看还是只能自己为轨道命名来区分。

我注意到了 **“文件名除“视频名”以外的部分目前会作为轨道Title输入给mkvmerge”** 所以目前我是将字幕命名中带“简体中文”和“繁体中文”来实现我的上述需求的。

也确实存在如果用户不规范自定义文件名导致很难匹配轨道语言信息的问题，所以我的意思其实是类似于只在其中加入ISO-639编码来匹配，并且给予此功能一个开关。如果开启，那么不管文件名剩余部分总共有什么，只要包含“chi，zh”等都将此轨道匹配为chi [中文]。对于在其中偶然使用了这些标签的用户可以选择关闭此功能。

在此之外支持用户自己导入映射表来自定义也可以，不过也需要开发者来指导用户编写映射表，不算很轻松😳

**Comment by DYY-Studio** [comment]
具体实现形式我再想想吧，最近一时半会也憋不出来这么大更新就是了）别的事情还欠了一屁股，可能要到9月份吧
