### ISSUE TITLE
特效字幕，子集化后，一些字体会错位

### ISSUE THREAD

**Issue by Nahuimi** [DYY-Studio/AddSubFontMKV_py#43]
00：49 正常
![0049-正常](https://github.com/user-attachments/assets/053b42a9-7f65-4c98-ac71-c6249763bd99)
子集化后
![0049-不正常](https://github.com/user-attachments/assets/f073160e-b205-4b1e-96e4-7a81834d3669)

14：55
正常
![1455-正常](https://github.com/user-attachments/assets/4767cfc2-07ee-46e4-9b46-0e410abc3b57)

子集化后
![1455-不正常](https://github.com/user-attachments/assets/6269985b-7e54-4203-92d8-e140fa5b1f1d)

通过对比发现，子集化后少了东西
<img width="1211" alt="截图：20240924164932" src="https://github.com/user-attachments/assets/7dfeda0b-0604-4182-be61-f8ecd62f720c">

~~~
Dialogue: 0,0:15:03.74,0:15:05.93,JPN-Monotone,,0,0,0,,{\fad(300,0)} {\blur5\3c9192FF\bord2\pos(960,1060)}美和が言ってたよ
~~~
~~~
Dialogue: 0,0:15:03.74,0:15:05.93,JPN-Monotone,,0,0,0,, 美和が言ってたよ
~~~

原本的字幕和子集化后的字幕
[sub-3.zip](https://github.com/user-attachments/files/17111407/sub-3.zip)

原本的字幕和字体包
https://github.com/HaruhanaSub/Haruhana-Fansub_Source/tree/main/Shigatsu%20wa%20Kimi%20no%20Uso

**Comment by DYY-Studio** [comment]
<s>我猜是Pre21改的新函数的问题。

可能是Pre21时换用字典存储ASS/SSA信息了。字典传递时是引用的，但当时我没注意，没有做deepcopy，在对特效标签做切割的时候同时也删掉了主字典里的特效标签。

理论上是这样的…？应该是一个deepcopy就可以解决的事情。

可以尝试在第374行把
`events = assInfo['Events']`
改为
`events = copy.deepcopy(assInfo['Events'])`

具体要等我回到电脑前调试才知道</s>

知道了，但是处理起来有点棘手。
是Pre20之前的老版本标签处理算法和Pre20之后的新存储方式有矛盾。

修完了，之后会和仅字幕MKS封装一起释出。

**Comment by Nahuimi** [comment]
使用ASFMKV_pre25，字体是没错位了，但是特效删掉了
正常
![2207](https://github.com/user-attachments/assets/e2211364-4e8d-4c3b-a6c9-3b107e702d6b)
子集化后
![2207 (2)](https://github.com/user-attachments/assets/a2bd7120-8b51-4930-b646-4755cf4ebc44)

字幕文件的体积也从35m，变成16m，体积少了一半
子集化不是把原本的字体名称，替换成子集化后的字体名称就可以了吗？其他都不用改什么吧，还是我的认知有问题

**Comment by DYY-Studio** [comment]
认知没问题，这也是个陈年旧事了。
是个bug。

之前都没有对这么大规模的特效做过测试。
尤其是矢量绘图，这部分一直是未经验证的。

Pre20在分析算法上有大改，这应该也是老算法和新算法逻辑不匹配的问题）

因为ASS/SSA分析和替换这块不是现成方案而是手搓的）

减少的体积就是矢量绘图部分被误删了。

**Comment by Nahuimi** [comment]
> 认知没问题，这也是个陈年旧事了。 是个bug。
> 
> 之前都没有对这么大规模的特效做过测试。 尤其是矢量绘图，这部分一直是未经验证的。
> 
> Pre20在分析算法上有大改，这应该也是老算法和新算法逻辑不匹配的问题）
> 
> 因为ASS/SSA分析和替换这块不是现成方案而是手搓的）
> 
> 减少的体积就是矢量绘图部分被误删了。

感谢修复，可以了
